# -*- coding: utf-8 -*-

BACKLOG_COST = 1.0
INVENTORY_COST = 0.5

GAME_LEGTH = 50

ORDER_DELAY = 2
TRANSPORT_DELAY = 2

INVENTORY_INITIAL = 12
DELAY_TRANSPORT_INITIAL = 4

MAX_CUSTOMER_ORDER = 8
MIN_CUSTOMER_ORDER = 0